

-- | <fullname>Amazon Inspector</fullname> <p>Amazon Inspector enables you to analyze the behavior of your AWS resources and to identify potential security issues. For more information, see <a href="http://docs.aws.amazon.com/inspector/latest/userguide/inspector_introduction.html"> Amazon Inspector User Guide</a>.</p>
module AWS.Inspector where

import Control.Monad.Aff (Aff)
import Data.Foreign.NullOrUndefined (NullOrUndefined)
import Data.Map (Map)
import Data.Newtype (class Newtype)
import Data.Unit (Unit, unit)

import AWS.Request as AWS

serviceName = "Inspector" :: String


-- | <p>Assigns attributes (key and value pairs) to the findings that are specified by the ARNs of the findings.</p>
addAttributesToFindings :: forall eff. AddAttributesToFindingsRequest -> Aff (err :: AWS.RequestError | eff) AddAttributesToFindingsResponse
addAttributesToFindings = AWS.request serviceName "AddAttributesToFindings" 


-- | <p>Creates a new assessment target using the ARN of the resource group that is generated by <a>CreateResourceGroup</a>. If the <a href="https://docs.aws.amazon.com/inspector/latest/userguide/inspector_slr.html">service-linked role</a> isn’t already registered, also creates and registers a service-linked role to grant Amazon Inspector access to AWS Services needed to perform security assessments. You can create up to 50 assessment targets per AWS account. You can run up to 500 concurrent agents per AWS account. For more information, see <a href="http://docs.aws.amazon.com/inspector/latest/userguide/inspector_applications.html"> Amazon Inspector Assessment Targets</a>.</p>
createAssessmentTarget :: forall eff. CreateAssessmentTargetRequest -> Aff (err :: AWS.RequestError | eff) CreateAssessmentTargetResponse
createAssessmentTarget = AWS.request serviceName "CreateAssessmentTarget" 


-- | <p>Creates an assessment template for the assessment target that is specified by the ARN of the assessment target. If the <a href="https://docs.aws.amazon.com/inspector/latest/userguide/inspector_slr.html">service-linked role</a> isn’t already registered, also creates and registers a service-linked role to grant Amazon Inspector access to AWS Services needed to perform security assessments.</p>
createAssessmentTemplate :: forall eff. CreateAssessmentTemplateRequest -> Aff (err :: AWS.RequestError | eff) CreateAssessmentTemplateResponse
createAssessmentTemplate = AWS.request serviceName "CreateAssessmentTemplate" 


-- | <p>Creates a resource group using the specified set of tags (key and value pairs) that are used to select the EC2 instances to be included in an Amazon Inspector assessment target. The created resource group is then used to create an Amazon Inspector assessment target. For more information, see <a>CreateAssessmentTarget</a>.</p>
createResourceGroup :: forall eff. CreateResourceGroupRequest -> Aff (err :: AWS.RequestError | eff) CreateResourceGroupResponse
createResourceGroup = AWS.request serviceName "CreateResourceGroup" 


-- | <p>Deletes the assessment run that is specified by the ARN of the assessment run.</p>
deleteAssessmentRun :: forall eff. DeleteAssessmentRunRequest -> Aff (err :: AWS.RequestError | eff) Unit
deleteAssessmentRun = AWS.request serviceName "DeleteAssessmentRun" 


-- | <p>Deletes the assessment target that is specified by the ARN of the assessment target.</p>
deleteAssessmentTarget :: forall eff. DeleteAssessmentTargetRequest -> Aff (err :: AWS.RequestError | eff) Unit
deleteAssessmentTarget = AWS.request serviceName "DeleteAssessmentTarget" 


-- | <p>Deletes the assessment template that is specified by the ARN of the assessment template.</p>
deleteAssessmentTemplate :: forall eff. DeleteAssessmentTemplateRequest -> Aff (err :: AWS.RequestError | eff) Unit
deleteAssessmentTemplate = AWS.request serviceName "DeleteAssessmentTemplate" 


-- | <p>Describes the assessment runs that are specified by the ARNs of the assessment runs.</p>
describeAssessmentRuns :: forall eff. DescribeAssessmentRunsRequest -> Aff (err :: AWS.RequestError | eff) DescribeAssessmentRunsResponse
describeAssessmentRuns = AWS.request serviceName "DescribeAssessmentRuns" 


-- | <p>Describes the assessment targets that are specified by the ARNs of the assessment targets.</p>
describeAssessmentTargets :: forall eff. DescribeAssessmentTargetsRequest -> Aff (err :: AWS.RequestError | eff) DescribeAssessmentTargetsResponse
describeAssessmentTargets = AWS.request serviceName "DescribeAssessmentTargets" 


-- | <p>Describes the assessment templates that are specified by the ARNs of the assessment templates.</p>
describeAssessmentTemplates :: forall eff. DescribeAssessmentTemplatesRequest -> Aff (err :: AWS.RequestError | eff) DescribeAssessmentTemplatesResponse
describeAssessmentTemplates = AWS.request serviceName "DescribeAssessmentTemplates" 


-- | <p>Describes the IAM role that enables Amazon Inspector to access your AWS account.</p>
describeCrossAccountAccessRole :: forall eff.  Aff (err :: AWS.RequestError | eff) DescribeCrossAccountAccessRoleResponse
describeCrossAccountAccessRole = AWS.request serviceName "DescribeCrossAccountAccessRole" unit


-- | <p>Describes the findings that are specified by the ARNs of the findings.</p>
describeFindings :: forall eff. DescribeFindingsRequest -> Aff (err :: AWS.RequestError | eff) DescribeFindingsResponse
describeFindings = AWS.request serviceName "DescribeFindings" 


-- | <p>Describes the resource groups that are specified by the ARNs of the resource groups.</p>
describeResourceGroups :: forall eff. DescribeResourceGroupsRequest -> Aff (err :: AWS.RequestError | eff) DescribeResourceGroupsResponse
describeResourceGroups = AWS.request serviceName "DescribeResourceGroups" 


-- | <p>Describes the rules packages that are specified by the ARNs of the rules packages.</p>
describeRulesPackages :: forall eff. DescribeRulesPackagesRequest -> Aff (err :: AWS.RequestError | eff) DescribeRulesPackagesResponse
describeRulesPackages = AWS.request serviceName "DescribeRulesPackages" 


-- | <p>Produces an assessment report that includes detailed and comprehensive results of a specified assessment run. </p>
getAssessmentReport :: forall eff. GetAssessmentReportRequest -> Aff (err :: AWS.RequestError | eff) GetAssessmentReportResponse
getAssessmentReport = AWS.request serviceName "GetAssessmentReport" 


-- | <p>Information about the data that is collected for the specified assessment run.</p>
getTelemetryMetadata :: forall eff. GetTelemetryMetadataRequest -> Aff (err :: AWS.RequestError | eff) GetTelemetryMetadataResponse
getTelemetryMetadata = AWS.request serviceName "GetTelemetryMetadata" 


-- | <p>Lists the agents of the assessment runs that are specified by the ARNs of the assessment runs.</p>
listAssessmentRunAgents :: forall eff. ListAssessmentRunAgentsRequest -> Aff (err :: AWS.RequestError | eff) ListAssessmentRunAgentsResponse
listAssessmentRunAgents = AWS.request serviceName "ListAssessmentRunAgents" 


-- | <p>Lists the assessment runs that correspond to the assessment templates that are specified by the ARNs of the assessment templates.</p>
listAssessmentRuns :: forall eff. ListAssessmentRunsRequest -> Aff (err :: AWS.RequestError | eff) ListAssessmentRunsResponse
listAssessmentRuns = AWS.request serviceName "ListAssessmentRuns" 


-- | <p>Lists the ARNs of the assessment targets within this AWS account. For more information about assessment targets, see <a href="http://docs.aws.amazon.com/inspector/latest/userguide/inspector_applications.html">Amazon Inspector Assessment Targets</a>.</p>
listAssessmentTargets :: forall eff. ListAssessmentTargetsRequest -> Aff (err :: AWS.RequestError | eff) ListAssessmentTargetsResponse
listAssessmentTargets = AWS.request serviceName "ListAssessmentTargets" 


-- | <p>Lists the assessment templates that correspond to the assessment targets that are specified by the ARNs of the assessment targets.</p>
listAssessmentTemplates :: forall eff. ListAssessmentTemplatesRequest -> Aff (err :: AWS.RequestError | eff) ListAssessmentTemplatesResponse
listAssessmentTemplates = AWS.request serviceName "ListAssessmentTemplates" 


-- | <p>Lists all the event subscriptions for the assessment template that is specified by the ARN of the assessment template. For more information, see <a>SubscribeToEvent</a> and <a>UnsubscribeFromEvent</a>.</p>
listEventSubscriptions :: forall eff. ListEventSubscriptionsRequest -> Aff (err :: AWS.RequestError | eff) ListEventSubscriptionsResponse
listEventSubscriptions = AWS.request serviceName "ListEventSubscriptions" 


-- | <p>Lists findings that are generated by the assessment runs that are specified by the ARNs of the assessment runs.</p>
listFindings :: forall eff. ListFindingsRequest -> Aff (err :: AWS.RequestError | eff) ListFindingsResponse
listFindings = AWS.request serviceName "ListFindings" 


-- | <p>Lists all available Amazon Inspector rules packages.</p>
listRulesPackages :: forall eff. ListRulesPackagesRequest -> Aff (err :: AWS.RequestError | eff) ListRulesPackagesResponse
listRulesPackages = AWS.request serviceName "ListRulesPackages" 


-- | <p>Lists all tags associated with an assessment template.</p>
listTagsForResource :: forall eff. ListTagsForResourceRequest -> Aff (err :: AWS.RequestError | eff) ListTagsForResourceResponse
listTagsForResource = AWS.request serviceName "ListTagsForResource" 


-- | <p>Previews the agents installed on the EC2 instances that are part of the specified assessment target.</p>
previewAgents :: forall eff. PreviewAgentsRequest -> Aff (err :: AWS.RequestError | eff) PreviewAgentsResponse
previewAgents = AWS.request serviceName "PreviewAgents" 


-- | <p>Registers the IAM role that grants Amazon Inspector access to AWS Services needed to perform security assessments.</p>
registerCrossAccountAccessRole :: forall eff. RegisterCrossAccountAccessRoleRequest -> Aff (err :: AWS.RequestError | eff) Unit
registerCrossAccountAccessRole = AWS.request serviceName "RegisterCrossAccountAccessRole" 


-- | <p>Removes entire attributes (key and value pairs) from the findings that are specified by the ARNs of the findings where an attribute with the specified key exists.</p>
removeAttributesFromFindings :: forall eff. RemoveAttributesFromFindingsRequest -> Aff (err :: AWS.RequestError | eff) RemoveAttributesFromFindingsResponse
removeAttributesFromFindings = AWS.request serviceName "RemoveAttributesFromFindings" 


-- | <p>Sets tags (key and value pairs) to the assessment template that is specified by the ARN of the assessment template.</p>
setTagsForResource :: forall eff. SetTagsForResourceRequest -> Aff (err :: AWS.RequestError | eff) Unit
setTagsForResource = AWS.request serviceName "SetTagsForResource" 


-- | <p>Starts the assessment run specified by the ARN of the assessment template. For this API to function properly, you must not exceed the limit of running up to 500 concurrent agents per AWS account.</p>
startAssessmentRun :: forall eff. StartAssessmentRunRequest -> Aff (err :: AWS.RequestError | eff) StartAssessmentRunResponse
startAssessmentRun = AWS.request serviceName "StartAssessmentRun" 


-- | <p>Stops the assessment run that is specified by the ARN of the assessment run.</p>
stopAssessmentRun :: forall eff. StopAssessmentRunRequest -> Aff (err :: AWS.RequestError | eff) Unit
stopAssessmentRun = AWS.request serviceName "StopAssessmentRun" 


-- | <p>Enables the process of sending Amazon Simple Notification Service (SNS) notifications about a specified event to a specified SNS topic.</p>
subscribeToEvent :: forall eff. SubscribeToEventRequest -> Aff (err :: AWS.RequestError | eff) Unit
subscribeToEvent = AWS.request serviceName "SubscribeToEvent" 


-- | <p>Disables the process of sending Amazon Simple Notification Service (SNS) notifications about a specified event to a specified SNS topic.</p>
unsubscribeFromEvent :: forall eff. UnsubscribeFromEventRequest -> Aff (err :: AWS.RequestError | eff) Unit
unsubscribeFromEvent = AWS.request serviceName "UnsubscribeFromEvent" 


-- | <p>Updates the assessment target that is specified by the ARN of the assessment target.</p>
updateAssessmentTarget :: forall eff. UpdateAssessmentTargetRequest -> Aff (err :: AWS.RequestError | eff) Unit
updateAssessmentTarget = AWS.request serviceName "UpdateAssessmentTarget" 


newtype AccessDeniedErrorCode = AccessDeniedErrorCode String
derive instance newtypeAccessDeniedErrorCode :: Newtype AccessDeniedErrorCode _


-- | <p>You do not have required permissions to access the requested resource.</p>
newtype AccessDeniedException = AccessDeniedException 
  { "Message'" :: (ErrorMessage)
  , "ErrorCode'" :: (AccessDeniedErrorCode)
  , "CanRetry'" :: (Bool)
  }
derive instance newtypeAccessDeniedException :: Newtype AccessDeniedException _


newtype AddAttributesToFindingsRequest = AddAttributesToFindingsRequest 
  { "FindingArns'" :: (AddRemoveAttributesFindingArnList)
  , "Attributes'" :: (UserAttributeList)
  }
derive instance newtypeAddAttributesToFindingsRequest :: Newtype AddAttributesToFindingsRequest _


newtype AddAttributesToFindingsResponse = AddAttributesToFindingsResponse 
  { "FailedItems'" :: (FailedItems)
  }
derive instance newtypeAddAttributesToFindingsResponse :: Newtype AddAttributesToFindingsResponse _


newtype AddRemoveAttributesFindingArnList = AddRemoveAttributesFindingArnList (Array Arn)
derive instance newtypeAddRemoveAttributesFindingArnList :: Newtype AddRemoveAttributesFindingArnList _


-- | <p>Used in the exception error that is thrown if you start an assessment run for an assessment target that includes an EC2 instance that is already participating in another started assessment run.</p>
newtype AgentAlreadyRunningAssessment = AgentAlreadyRunningAssessment 
  { "AgentId'" :: (AgentId)
  , "AssessmentRunArn'" :: (Arn)
  }
derive instance newtypeAgentAlreadyRunningAssessment :: Newtype AgentAlreadyRunningAssessment _


newtype AgentAlreadyRunningAssessmentList = AgentAlreadyRunningAssessmentList (Array AgentAlreadyRunningAssessment)
derive instance newtypeAgentAlreadyRunningAssessmentList :: Newtype AgentAlreadyRunningAssessmentList _


-- | <p>Contains information about an Amazon Inspector agent. This data type is used as a request parameter in the <a>ListAssessmentRunAgents</a> action.</p>
newtype AgentFilter = AgentFilter 
  { "AgentHealths'" :: (AgentHealthList)
  , "AgentHealthCodes'" :: (AgentHealthCodeList)
  }
derive instance newtypeAgentFilter :: Newtype AgentFilter _


newtype AgentHealth = AgentHealth String
derive instance newtypeAgentHealth :: Newtype AgentHealth _


newtype AgentHealthCode = AgentHealthCode String
derive instance newtypeAgentHealthCode :: Newtype AgentHealthCode _


newtype AgentHealthCodeList = AgentHealthCodeList (Array AgentHealthCode)
derive instance newtypeAgentHealthCodeList :: Newtype AgentHealthCodeList _


newtype AgentHealthList = AgentHealthList (Array AgentHealth)
derive instance newtypeAgentHealthList :: Newtype AgentHealthList _


newtype AgentId = AgentId String
derive instance newtypeAgentId :: Newtype AgentId _


newtype AgentIdList = AgentIdList (Array AgentId)
derive instance newtypeAgentIdList :: Newtype AgentIdList _


-- | <p>Used as a response element in the <a>PreviewAgents</a> action.</p>
newtype AgentPreview = AgentPreview 
  { "Hostname'" :: NullOrUndefined (Hostname)
  , "AgentId'" :: (AgentId)
  , "AutoScalingGroup'" :: NullOrUndefined (AutoScalingGroup)
  , "AgentHealth'" :: NullOrUndefined (AgentHealth)
  , "AgentVersion'" :: NullOrUndefined (AgentVersion)
  , "OperatingSystem'" :: NullOrUndefined (OperatingSystem)
  , "KernelVersion'" :: NullOrUndefined (KernelVersion)
  , "Ipv4Address'" :: NullOrUndefined (Ipv4Address)
  }
derive instance newtypeAgentPreview :: Newtype AgentPreview _


newtype AgentPreviewList = AgentPreviewList (Array AgentPreview)
derive instance newtypeAgentPreviewList :: Newtype AgentPreviewList _


newtype AgentVersion = AgentVersion String
derive instance newtypeAgentVersion :: Newtype AgentVersion _


-- | <p>You started an assessment run, but one of the instances is already participating in another assessment run.</p>
newtype AgentsAlreadyRunningAssessmentException = AgentsAlreadyRunningAssessmentException 
  { "Message'" :: (ErrorMessage)
  , "Agents'" :: (AgentAlreadyRunningAssessmentList)
  , "AgentsTruncated'" :: (Bool)
  , "CanRetry'" :: (Bool)
  }
derive instance newtypeAgentsAlreadyRunningAssessmentException :: Newtype AgentsAlreadyRunningAssessmentException _


newtype AmiId = AmiId String
derive instance newtypeAmiId :: Newtype AmiId _


newtype Arn = Arn String
derive instance newtypeArn :: Newtype Arn _


newtype ArnCount = ArnCount Int
derive instance newtypeArnCount :: Newtype ArnCount _


newtype AssessmentRulesPackageArnList = AssessmentRulesPackageArnList (Array Arn)
derive instance newtypeAssessmentRulesPackageArnList :: Newtype AssessmentRulesPackageArnList _


-- | <p>A snapshot of an Amazon Inspector assessment run that contains the findings of the assessment run .</p> <p>Used as the response element in the <a>DescribeAssessmentRuns</a> action.</p>
newtype AssessmentRun = AssessmentRun 
  { "Arn'" :: (Arn)
  , "Name'" :: (AssessmentRunName)
  , "AssessmentTemplateArn'" :: (Arn)
  , "State'" :: (AssessmentRunState)
  , "DurationInSeconds'" :: (AssessmentRunDuration)
  , "RulesPackageArns'" :: (AssessmentRulesPackageArnList)
  , "UserAttributesForFindings'" :: (UserAttributeList)
  , "CreatedAt'" :: (Number)
  , "StartedAt'" :: NullOrUndefined (Number)
  , "CompletedAt'" :: NullOrUndefined (Number)
  , "StateChangedAt'" :: (Number)
  , "DataCollected'" :: (Bool)
  , "StateChanges'" :: (AssessmentRunStateChangeList)
  , "Notifications'" :: (AssessmentRunNotificationList)
  , "FindingCounts'" :: (AssessmentRunFindingCounts)
  }
derive instance newtypeAssessmentRun :: Newtype AssessmentRun _


-- | <p>Contains information about an Amazon Inspector agent. This data type is used as a response element in the <a>ListAssessmentRunAgents</a> action.</p>
newtype AssessmentRunAgent = AssessmentRunAgent 
  { "AgentId'" :: (AgentId)
  , "AssessmentRunArn'" :: (Arn)
  , "AgentHealth'" :: (AgentHealth)
  , "AgentHealthCode'" :: (AgentHealthCode)
  , "AgentHealthDetails'" :: NullOrUndefined (Message)
  , "AutoScalingGroup'" :: NullOrUndefined (AutoScalingGroup)
  , "TelemetryMetadata'" :: (TelemetryMetadataList)
  }
derive instance newtypeAssessmentRunAgent :: Newtype AssessmentRunAgent _


newtype AssessmentRunAgentList = AssessmentRunAgentList (Array AssessmentRunAgent)
derive instance newtypeAssessmentRunAgentList :: Newtype AssessmentRunAgentList _


newtype AssessmentRunDuration = AssessmentRunDuration Int
derive instance newtypeAssessmentRunDuration :: Newtype AssessmentRunDuration _


-- | <p>Used as the request parameter in the <a>ListAssessmentRuns</a> action.</p>
newtype AssessmentRunFilter = AssessmentRunFilter 
  { "NamePattern'" :: NullOrUndefined (NamePattern)
  , "States'" :: NullOrUndefined (AssessmentRunStateList)
  , "DurationRange'" :: NullOrUndefined (DurationRange)
  , "RulesPackageArns'" :: NullOrUndefined (FilterRulesPackageArnList)
  , "StartTimeRange'" :: NullOrUndefined (TimestampRange)
  , "CompletionTimeRange'" :: NullOrUndefined (TimestampRange)
  , "StateChangeTimeRange'" :: NullOrUndefined (TimestampRange)
  }
derive instance newtypeAssessmentRunFilter :: Newtype AssessmentRunFilter _


newtype AssessmentRunFindingCounts = AssessmentRunFindingCounts (Map Severity FindingCount)
derive instance newtypeAssessmentRunFindingCounts :: Newtype AssessmentRunFindingCounts _


newtype AssessmentRunInProgressArnList = AssessmentRunInProgressArnList (Array Arn)
derive instance newtypeAssessmentRunInProgressArnList :: Newtype AssessmentRunInProgressArnList _


-- | <p>You cannot perform a specified action if an assessment run is currently in progress.</p>
newtype AssessmentRunInProgressException = AssessmentRunInProgressException 
  { "Message'" :: (ErrorMessage)
  , "AssessmentRunArns'" :: (AssessmentRunInProgressArnList)
  , "AssessmentRunArnsTruncated'" :: (Bool)
  , "CanRetry'" :: (Bool)
  }
derive instance newtypeAssessmentRunInProgressException :: Newtype AssessmentRunInProgressException _


newtype AssessmentRunList = AssessmentRunList (Array AssessmentRun)
derive instance newtypeAssessmentRunList :: Newtype AssessmentRunList _


newtype AssessmentRunName = AssessmentRunName String
derive instance newtypeAssessmentRunName :: Newtype AssessmentRunName _


-- | <p>Used as one of the elements of the <a>AssessmentRun</a> data type.</p>
newtype AssessmentRunNotification = AssessmentRunNotification 
  { "Date'" :: (Number)
  , "Event'" :: (InspectorEvent)
  , "Message'" :: NullOrUndefined (Message)
  , "Error'" :: (Bool)
  , "SnsTopicArn'" :: NullOrUndefined (Arn)
  , "SnsPublishStatusCode'" :: NullOrUndefined (AssessmentRunNotificationSnsStatusCode)
  }
derive instance newtypeAssessmentRunNotification :: Newtype AssessmentRunNotification _


newtype AssessmentRunNotificationList = AssessmentRunNotificationList (Array AssessmentRunNotification)
derive instance newtypeAssessmentRunNotificationList :: Newtype AssessmentRunNotificationList _


newtype AssessmentRunNotificationSnsStatusCode = AssessmentRunNotificationSnsStatusCode String
derive instance newtypeAssessmentRunNotificationSnsStatusCode :: Newtype AssessmentRunNotificationSnsStatusCode _


newtype AssessmentRunState = AssessmentRunState String
derive instance newtypeAssessmentRunState :: Newtype AssessmentRunState _


-- | <p>Used as one of the elements of the <a>AssessmentRun</a> data type.</p>
newtype AssessmentRunStateChange = AssessmentRunStateChange 
  { "StateChangedAt'" :: (Number)
  , "State'" :: (AssessmentRunState)
  }
derive instance newtypeAssessmentRunStateChange :: Newtype AssessmentRunStateChange _


newtype AssessmentRunStateChangeList = AssessmentRunStateChangeList (Array AssessmentRunStateChange)
derive instance newtypeAssessmentRunStateChangeList :: Newtype AssessmentRunStateChangeList _


newtype AssessmentRunStateList = AssessmentRunStateList (Array AssessmentRunState)
derive instance newtypeAssessmentRunStateList :: Newtype AssessmentRunStateList _


-- | <p>Contains information about an Amazon Inspector application. This data type is used as the response element in the <a>DescribeAssessmentTargets</a> action.</p>
newtype AssessmentTarget = AssessmentTarget 
  { "Arn'" :: (Arn)
  , "Name'" :: (AssessmentTargetName)
  , "ResourceGroupArn'" :: (Arn)
  , "CreatedAt'" :: (Number)
  , "UpdatedAt'" :: (Number)
  }
derive instance newtypeAssessmentTarget :: Newtype AssessmentTarget _


-- | <p>Used as the request parameter in the <a>ListAssessmentTargets</a> action.</p>
newtype AssessmentTargetFilter = AssessmentTargetFilter 
  { "AssessmentTargetNamePattern'" :: NullOrUndefined (NamePattern)
  }
derive instance newtypeAssessmentTargetFilter :: Newtype AssessmentTargetFilter _


newtype AssessmentTargetList = AssessmentTargetList (Array AssessmentTarget)
derive instance newtypeAssessmentTargetList :: Newtype AssessmentTargetList _


newtype AssessmentTargetName = AssessmentTargetName String
derive instance newtypeAssessmentTargetName :: Newtype AssessmentTargetName _


-- | <p>Contains information about an Amazon Inspector assessment template. This data type is used as the response element in the <a>DescribeAssessmentTemplates</a> action.</p>
newtype AssessmentTemplate = AssessmentTemplate 
  { "Arn'" :: (Arn)
  , "Name'" :: (AssessmentTemplateName)
  , "AssessmentTargetArn'" :: (Arn)
  , "DurationInSeconds'" :: (AssessmentRunDuration)
  , "RulesPackageArns'" :: (AssessmentTemplateRulesPackageArnList)
  , "UserAttributesForFindings'" :: (UserAttributeList)
  , "LastAssessmentRunArn'" :: NullOrUndefined (Arn)
  , "AssessmentRunCount'" :: (ArnCount)
  , "CreatedAt'" :: (Number)
  }
derive instance newtypeAssessmentTemplate :: Newtype AssessmentTemplate _


-- | <p>Used as the request parameter in the <a>ListAssessmentTemplates</a> action.</p>
newtype AssessmentTemplateFilter = AssessmentTemplateFilter 
  { "NamePattern'" :: NullOrUndefined (NamePattern)
  , "DurationRange'" :: NullOrUndefined (DurationRange)
  , "RulesPackageArns'" :: NullOrUndefined (FilterRulesPackageArnList)
  }
derive instance newtypeAssessmentTemplateFilter :: Newtype AssessmentTemplateFilter _


newtype AssessmentTemplateList = AssessmentTemplateList (Array AssessmentTemplate)
derive instance newtypeAssessmentTemplateList :: Newtype AssessmentTemplateList _


newtype AssessmentTemplateName = AssessmentTemplateName String
derive instance newtypeAssessmentTemplateName :: Newtype AssessmentTemplateName _


newtype AssessmentTemplateRulesPackageArnList = AssessmentTemplateRulesPackageArnList (Array Arn)
derive instance newtypeAssessmentTemplateRulesPackageArnList :: Newtype AssessmentTemplateRulesPackageArnList _


-- | <p>A collection of attributes of the host from which the finding is generated.</p>
newtype AssetAttributes = AssetAttributes 
  { "SchemaVersion'" :: (NumericVersion)
  , "AgentId'" :: NullOrUndefined (AgentId)
  , "AutoScalingGroup'" :: NullOrUndefined (AutoScalingGroup)
  , "AmiId'" :: NullOrUndefined (AmiId)
  , "Hostname'" :: NullOrUndefined (Hostname)
  , "Ipv4Addresses'" :: NullOrUndefined (Ipv4AddressList)
  }
derive instance newtypeAssetAttributes :: Newtype AssetAttributes _


newtype AssetType = AssetType String
derive instance newtypeAssetType :: Newtype AssetType _


-- | <p>This data type is used as a request parameter in the <a>AddAttributesToFindings</a> and <a>CreateAssessmentTemplate</a> actions.</p>
newtype Attribute = Attribute 
  { "Key'" :: (AttributeKey)
  , "Value'" :: NullOrUndefined (AttributeValue)
  }
derive instance newtypeAttribute :: Newtype Attribute _


newtype AttributeKey = AttributeKey String
derive instance newtypeAttributeKey :: Newtype AttributeKey _


newtype AttributeList = AttributeList (Array Attribute)
derive instance newtypeAttributeList :: Newtype AttributeList _


newtype AttributeValue = AttributeValue String
derive instance newtypeAttributeValue :: Newtype AttributeValue _


newtype AutoScalingGroup = AutoScalingGroup String
derive instance newtypeAutoScalingGroup :: Newtype AutoScalingGroup _


newtype AutoScalingGroupList = AutoScalingGroupList (Array AutoScalingGroup)
derive instance newtypeAutoScalingGroupList :: Newtype AutoScalingGroupList _


newtype BatchDescribeArnList = BatchDescribeArnList (Array Arn)
derive instance newtypeBatchDescribeArnList :: Newtype BatchDescribeArnList _


newtype Bool = Bool Boolean
derive instance newtypeBool :: Newtype Bool _


newtype CreateAssessmentTargetRequest = CreateAssessmentTargetRequest 
  { "AssessmentTargetName'" :: (AssessmentTargetName)
  , "ResourceGroupArn'" :: (Arn)
  }
derive instance newtypeCreateAssessmentTargetRequest :: Newtype CreateAssessmentTargetRequest _


newtype CreateAssessmentTargetResponse = CreateAssessmentTargetResponse 
  { "AssessmentTargetArn'" :: (Arn)
  }
derive instance newtypeCreateAssessmentTargetResponse :: Newtype CreateAssessmentTargetResponse _


newtype CreateAssessmentTemplateRequest = CreateAssessmentTemplateRequest 
  { "AssessmentTargetArn'" :: (Arn)
  , "AssessmentTemplateName'" :: (AssessmentTemplateName)
  , "DurationInSeconds'" :: (AssessmentRunDuration)
  , "RulesPackageArns'" :: (AssessmentTemplateRulesPackageArnList)
  , "UserAttributesForFindings'" :: NullOrUndefined (UserAttributeList)
  }
derive instance newtypeCreateAssessmentTemplateRequest :: Newtype CreateAssessmentTemplateRequest _


newtype CreateAssessmentTemplateResponse = CreateAssessmentTemplateResponse 
  { "AssessmentTemplateArn'" :: (Arn)
  }
derive instance newtypeCreateAssessmentTemplateResponse :: Newtype CreateAssessmentTemplateResponse _


newtype CreateResourceGroupRequest = CreateResourceGroupRequest 
  { "ResourceGroupTags'" :: (ResourceGroupTags)
  }
derive instance newtypeCreateResourceGroupRequest :: Newtype CreateResourceGroupRequest _


newtype CreateResourceGroupResponse = CreateResourceGroupResponse 
  { "ResourceGroupArn'" :: (Arn)
  }
derive instance newtypeCreateResourceGroupResponse :: Newtype CreateResourceGroupResponse _


newtype DeleteAssessmentRunRequest = DeleteAssessmentRunRequest 
  { "AssessmentRunArn'" :: (Arn)
  }
derive instance newtypeDeleteAssessmentRunRequest :: Newtype DeleteAssessmentRunRequest _


newtype DeleteAssessmentTargetRequest = DeleteAssessmentTargetRequest 
  { "AssessmentTargetArn'" :: (Arn)
  }
derive instance newtypeDeleteAssessmentTargetRequest :: Newtype DeleteAssessmentTargetRequest _


newtype DeleteAssessmentTemplateRequest = DeleteAssessmentTemplateRequest 
  { "AssessmentTemplateArn'" :: (Arn)
  }
derive instance newtypeDeleteAssessmentTemplateRequest :: Newtype DeleteAssessmentTemplateRequest _


newtype DescribeAssessmentRunsRequest = DescribeAssessmentRunsRequest 
  { "AssessmentRunArns'" :: (BatchDescribeArnList)
  }
derive instance newtypeDescribeAssessmentRunsRequest :: Newtype DescribeAssessmentRunsRequest _


newtype DescribeAssessmentRunsResponse = DescribeAssessmentRunsResponse 
  { "AssessmentRuns'" :: (AssessmentRunList)
  , "FailedItems'" :: (FailedItems)
  }
derive instance newtypeDescribeAssessmentRunsResponse :: Newtype DescribeAssessmentRunsResponse _


newtype DescribeAssessmentTargetsRequest = DescribeAssessmentTargetsRequest 
  { "AssessmentTargetArns'" :: (BatchDescribeArnList)
  }
derive instance newtypeDescribeAssessmentTargetsRequest :: Newtype DescribeAssessmentTargetsRequest _


newtype DescribeAssessmentTargetsResponse = DescribeAssessmentTargetsResponse 
  { "AssessmentTargets'" :: (AssessmentTargetList)
  , "FailedItems'" :: (FailedItems)
  }
derive instance newtypeDescribeAssessmentTargetsResponse :: Newtype DescribeAssessmentTargetsResponse _


newtype DescribeAssessmentTemplatesRequest = DescribeAssessmentTemplatesRequest 
  { "AssessmentTemplateArns'" :: (BatchDescribeArnList)
  }
derive instance newtypeDescribeAssessmentTemplatesRequest :: Newtype DescribeAssessmentTemplatesRequest _


newtype DescribeAssessmentTemplatesResponse = DescribeAssessmentTemplatesResponse 
  { "AssessmentTemplates'" :: (AssessmentTemplateList)
  , "FailedItems'" :: (FailedItems)
  }
derive instance newtypeDescribeAssessmentTemplatesResponse :: Newtype DescribeAssessmentTemplatesResponse _


newtype DescribeCrossAccountAccessRoleResponse = DescribeCrossAccountAccessRoleResponse 
  { "RoleArn'" :: (Arn)
  , "Valid'" :: (Bool)
  , "RegisteredAt'" :: (Number)
  }
derive instance newtypeDescribeCrossAccountAccessRoleResponse :: Newtype DescribeCrossAccountAccessRoleResponse _


newtype DescribeFindingsRequest = DescribeFindingsRequest 
  { "FindingArns'" :: (BatchDescribeArnList)
  , "Locale'" :: NullOrUndefined (Locale)
  }
derive instance newtypeDescribeFindingsRequest :: Newtype DescribeFindingsRequest _


newtype DescribeFindingsResponse = DescribeFindingsResponse 
  { "Findings'" :: (FindingList)
  , "FailedItems'" :: (FailedItems)
  }
derive instance newtypeDescribeFindingsResponse :: Newtype DescribeFindingsResponse _


newtype DescribeResourceGroupsRequest = DescribeResourceGroupsRequest 
  { "ResourceGroupArns'" :: (BatchDescribeArnList)
  }
derive instance newtypeDescribeResourceGroupsRequest :: Newtype DescribeResourceGroupsRequest _


newtype DescribeResourceGroupsResponse = DescribeResourceGroupsResponse 
  { "ResourceGroups'" :: (ResourceGroupList)
  , "FailedItems'" :: (FailedItems)
  }
derive instance newtypeDescribeResourceGroupsResponse :: Newtype DescribeResourceGroupsResponse _


newtype DescribeRulesPackagesRequest = DescribeRulesPackagesRequest 
  { "RulesPackageArns'" :: (BatchDescribeArnList)
  , "Locale'" :: NullOrUndefined (Locale)
  }
derive instance newtypeDescribeRulesPackagesRequest :: Newtype DescribeRulesPackagesRequest _


newtype DescribeRulesPackagesResponse = DescribeRulesPackagesResponse 
  { "RulesPackages'" :: (RulesPackageList)
  , "FailedItems'" :: (FailedItems)
  }
derive instance newtypeDescribeRulesPackagesResponse :: Newtype DescribeRulesPackagesResponse _


-- | <p>This data type is used in the <a>AssessmentTemplateFilter</a> data type.</p>
newtype DurationRange = DurationRange 
  { "MinSeconds'" :: NullOrUndefined (AssessmentRunDuration)
  , "MaxSeconds'" :: NullOrUndefined (AssessmentRunDuration)
  }
derive instance newtypeDurationRange :: Newtype DurationRange _


newtype ErrorMessage = ErrorMessage String
derive instance newtypeErrorMessage :: Newtype ErrorMessage _


-- | <p>This data type is used in the <a>Subscription</a> data type.</p>
newtype EventSubscription = EventSubscription 
  { "Event'" :: (InspectorEvent)
  , "SubscribedAt'" :: (Number)
  }
derive instance newtypeEventSubscription :: Newtype EventSubscription _


newtype EventSubscriptionList = EventSubscriptionList (Array EventSubscription)
derive instance newtypeEventSubscriptionList :: Newtype EventSubscriptionList _


-- | <p>Includes details about the failed items.</p>
newtype FailedItemDetails = FailedItemDetails 
  { "FailureCode'" :: (FailedItemErrorCode)
  , "Retryable'" :: (Bool)
  }
derive instance newtypeFailedItemDetails :: Newtype FailedItemDetails _


newtype FailedItemErrorCode = FailedItemErrorCode String
derive instance newtypeFailedItemErrorCode :: Newtype FailedItemErrorCode _


newtype FailedItems = FailedItems (Map Arn FailedItemDetails)
derive instance newtypeFailedItems :: Newtype FailedItems _


newtype FilterRulesPackageArnList = FilterRulesPackageArnList (Array Arn)
derive instance newtypeFilterRulesPackageArnList :: Newtype FilterRulesPackageArnList _


-- | <p>Contains information about an Amazon Inspector finding. This data type is used as the response element in the <a>DescribeFindings</a> action.</p>
newtype Finding = Finding 
  { "Arn'" :: (Arn)
  , "SchemaVersion'" :: NullOrUndefined (NumericVersion)
  , "Service'" :: NullOrUndefined (ServiceName)
  , "ServiceAttributes'" :: NullOrUndefined (InspectorServiceAttributes)
  , "AssetType'" :: NullOrUndefined (AssetType)
  , "AssetAttributes'" :: NullOrUndefined (AssetAttributes)
  , "Id'" :: NullOrUndefined (FindingId)
  , "Title'" :: NullOrUndefined (Text)
  , "Description'" :: NullOrUndefined (Text)
  , "Recommendation'" :: NullOrUndefined (Text)
  , "Severity'" :: NullOrUndefined (Severity)
  , "NumericSeverity'" :: NullOrUndefined (NumericSeverity)
  , "Confidence'" :: NullOrUndefined (IocConfidence)
  , "IndicatorOfCompromise'" :: NullOrUndefined (Bool)
  , "Attributes'" :: (AttributeList)
  , "UserAttributes'" :: (UserAttributeList)
  , "CreatedAt'" :: (Number)
  , "UpdatedAt'" :: (Number)
  }
derive instance newtypeFinding :: Newtype Finding _


newtype FindingCount = FindingCount Int
derive instance newtypeFindingCount :: Newtype FindingCount _


-- | <p>This data type is used as a request parameter in the <a>ListFindings</a> action.</p>
newtype FindingFilter = FindingFilter 
  { "AgentIds'" :: NullOrUndefined (AgentIdList)
  , "AutoScalingGroups'" :: NullOrUndefined (AutoScalingGroupList)
  , "RuleNames'" :: NullOrUndefined (RuleNameList)
  , "Severities'" :: NullOrUndefined (SeverityList)
  , "RulesPackageArns'" :: NullOrUndefined (FilterRulesPackageArnList)
  , "Attributes'" :: NullOrUndefined (AttributeList)
  , "UserAttributes'" :: NullOrUndefined (AttributeList)
  , "CreationTimeRange'" :: NullOrUndefined (TimestampRange)
  }
derive instance newtypeFindingFilter :: Newtype FindingFilter _


newtype FindingId = FindingId String
derive instance newtypeFindingId :: Newtype FindingId _


newtype FindingList = FindingList (Array Finding)
derive instance newtypeFindingList :: Newtype FindingList _


newtype GetAssessmentReportRequest = GetAssessmentReportRequest 
  { "AssessmentRunArn'" :: (Arn)
  , "ReportFileFormat'" :: (ReportFileFormat)
  , "ReportType'" :: (ReportType)
  }
derive instance newtypeGetAssessmentReportRequest :: Newtype GetAssessmentReportRequest _


newtype GetAssessmentReportResponse = GetAssessmentReportResponse 
  { "Status'" :: (ReportStatus)
  , "Url'" :: NullOrUndefined (Url)
  }
derive instance newtypeGetAssessmentReportResponse :: Newtype GetAssessmentReportResponse _


newtype GetTelemetryMetadataRequest = GetTelemetryMetadataRequest 
  { "AssessmentRunArn'" :: (Arn)
  }
derive instance newtypeGetTelemetryMetadataRequest :: Newtype GetTelemetryMetadataRequest _


newtype GetTelemetryMetadataResponse = GetTelemetryMetadataResponse 
  { "TelemetryMetadata'" :: (TelemetryMetadataList)
  }
derive instance newtypeGetTelemetryMetadataResponse :: Newtype GetTelemetryMetadataResponse _


newtype Hostname = Hostname String
derive instance newtypeHostname :: Newtype Hostname _


newtype InspectorEvent = InspectorEvent String
derive instance newtypeInspectorEvent :: Newtype InspectorEvent _


-- | <p>This data type is used in the <a>Finding</a> data type.</p>
newtype InspectorServiceAttributes = InspectorServiceAttributes 
  { "SchemaVersion'" :: (NumericVersion)
  , "AssessmentRunArn'" :: NullOrUndefined (Arn)
  , "RulesPackageArn'" :: NullOrUndefined (Arn)
  }
derive instance newtypeInspectorServiceAttributes :: Newtype InspectorServiceAttributes _


-- | <p>Internal server error.</p>
newtype InternalException = InternalException 
  { "Message'" :: (ErrorMessage)
  , "CanRetry'" :: (Bool)
  }
derive instance newtypeInternalException :: Newtype InternalException _


newtype InvalidCrossAccountRoleErrorCode = InvalidCrossAccountRoleErrorCode String
derive instance newtypeInvalidCrossAccountRoleErrorCode :: Newtype InvalidCrossAccountRoleErrorCode _


-- | <p>Amazon Inspector cannot assume the cross-account role that it needs to list your EC2 instances during the assessment run.</p>
newtype InvalidCrossAccountRoleException = InvalidCrossAccountRoleException 
  { "Message'" :: (ErrorMessage)
  , "ErrorCode'" :: (InvalidCrossAccountRoleErrorCode)
  , "CanRetry'" :: (Bool)
  }
derive instance newtypeInvalidCrossAccountRoleException :: Newtype InvalidCrossAccountRoleException _


newtype InvalidInputErrorCode = InvalidInputErrorCode String
derive instance newtypeInvalidInputErrorCode :: Newtype InvalidInputErrorCode _


-- | <p>The request was rejected because an invalid or out-of-range value was supplied for an input parameter.</p>
newtype InvalidInputException = InvalidInputException 
  { "Message'" :: (ErrorMessage)
  , "ErrorCode'" :: (InvalidInputErrorCode)
  , "CanRetry'" :: (Bool)
  }
derive instance newtypeInvalidInputException :: Newtype InvalidInputException _


newtype IocConfidence = IocConfidence Int
derive instance newtypeIocConfidence :: Newtype IocConfidence _


newtype Ipv4Address = Ipv4Address String
derive instance newtypeIpv4Address :: Newtype Ipv4Address _


newtype Ipv4AddressList = Ipv4AddressList (Array Ipv4Address)
derive instance newtypeIpv4AddressList :: Newtype Ipv4AddressList _


newtype KernelVersion = KernelVersion String
derive instance newtypeKernelVersion :: Newtype KernelVersion _


newtype LimitExceededErrorCode = LimitExceededErrorCode String
derive instance newtypeLimitExceededErrorCode :: Newtype LimitExceededErrorCode _


-- | <p>The request was rejected because it attempted to create resources beyond the current AWS account limits. The error code describes the limit exceeded.</p>
newtype LimitExceededException = LimitExceededException 
  { "Message'" :: (ErrorMessage)
  , "ErrorCode'" :: (LimitExceededErrorCode)
  , "CanRetry'" :: (Bool)
  }
derive instance newtypeLimitExceededException :: Newtype LimitExceededException _


newtype ListAssessmentRunAgentsRequest = ListAssessmentRunAgentsRequest 
  { "AssessmentRunArn'" :: (Arn)
  , "Filter'" :: NullOrUndefined (AgentFilter)
  , "NextToken'" :: NullOrUndefined (PaginationToken)
  , "MaxResults'" :: NullOrUndefined (ListMaxResults)
  }
derive instance newtypeListAssessmentRunAgentsRequest :: Newtype ListAssessmentRunAgentsRequest _


newtype ListAssessmentRunAgentsResponse = ListAssessmentRunAgentsResponse 
  { "AssessmentRunAgents'" :: (AssessmentRunAgentList)
  , "NextToken'" :: NullOrUndefined (PaginationToken)
  }
derive instance newtypeListAssessmentRunAgentsResponse :: Newtype ListAssessmentRunAgentsResponse _


newtype ListAssessmentRunsRequest = ListAssessmentRunsRequest 
  { "AssessmentTemplateArns'" :: NullOrUndefined (ListParentArnList)
  , "Filter'" :: NullOrUndefined (AssessmentRunFilter)
  , "NextToken'" :: NullOrUndefined (PaginationToken)
  , "MaxResults'" :: NullOrUndefined (ListMaxResults)
  }
derive instance newtypeListAssessmentRunsRequest :: Newtype ListAssessmentRunsRequest _


newtype ListAssessmentRunsResponse = ListAssessmentRunsResponse 
  { "AssessmentRunArns'" :: (ListReturnedArnList)
  , "NextToken'" :: NullOrUndefined (PaginationToken)
  }
derive instance newtypeListAssessmentRunsResponse :: Newtype ListAssessmentRunsResponse _


newtype ListAssessmentTargetsRequest = ListAssessmentTargetsRequest 
  { "Filter'" :: NullOrUndefined (AssessmentTargetFilter)
  , "NextToken'" :: NullOrUndefined (PaginationToken)
  , "MaxResults'" :: NullOrUndefined (ListMaxResults)
  }
derive instance newtypeListAssessmentTargetsRequest :: Newtype ListAssessmentTargetsRequest _


newtype ListAssessmentTargetsResponse = ListAssessmentTargetsResponse 
  { "AssessmentTargetArns'" :: (ListReturnedArnList)
  , "NextToken'" :: NullOrUndefined (PaginationToken)
  }
derive instance newtypeListAssessmentTargetsResponse :: Newtype ListAssessmentTargetsResponse _


newtype ListAssessmentTemplatesRequest = ListAssessmentTemplatesRequest 
  { "AssessmentTargetArns'" :: NullOrUndefined (ListParentArnList)
  , "Filter'" :: NullOrUndefined (AssessmentTemplateFilter)
  , "NextToken'" :: NullOrUndefined (PaginationToken)
  , "MaxResults'" :: NullOrUndefined (ListMaxResults)
  }
derive instance newtypeListAssessmentTemplatesRequest :: Newtype ListAssessmentTemplatesRequest _


newtype ListAssessmentTemplatesResponse = ListAssessmentTemplatesResponse 
  { "AssessmentTemplateArns'" :: (ListReturnedArnList)
  , "NextToken'" :: NullOrUndefined (PaginationToken)
  }
derive instance newtypeListAssessmentTemplatesResponse :: Newtype ListAssessmentTemplatesResponse _


newtype ListEventSubscriptionsMaxResults = ListEventSubscriptionsMaxResults Int
derive instance newtypeListEventSubscriptionsMaxResults :: Newtype ListEventSubscriptionsMaxResults _


newtype ListEventSubscriptionsRequest = ListEventSubscriptionsRequest 
  { "ResourceArn'" :: NullOrUndefined (Arn)
  , "NextToken'" :: NullOrUndefined (PaginationToken)
  , "MaxResults'" :: NullOrUndefined (ListEventSubscriptionsMaxResults)
  }
derive instance newtypeListEventSubscriptionsRequest :: Newtype ListEventSubscriptionsRequest _


newtype ListEventSubscriptionsResponse = ListEventSubscriptionsResponse 
  { "Subscriptions'" :: (SubscriptionList)
  , "NextToken'" :: NullOrUndefined (PaginationToken)
  }
derive instance newtypeListEventSubscriptionsResponse :: Newtype ListEventSubscriptionsResponse _


newtype ListFindingsRequest = ListFindingsRequest 
  { "AssessmentRunArns'" :: NullOrUndefined (ListParentArnList)
  , "Filter'" :: NullOrUndefined (FindingFilter)
  , "NextToken'" :: NullOrUndefined (PaginationToken)
  , "MaxResults'" :: NullOrUndefined (ListMaxResults)
  }
derive instance newtypeListFindingsRequest :: Newtype ListFindingsRequest _


newtype ListFindingsResponse = ListFindingsResponse 
  { "FindingArns'" :: (ListReturnedArnList)
  , "NextToken'" :: NullOrUndefined (PaginationToken)
  }
derive instance newtypeListFindingsResponse :: Newtype ListFindingsResponse _


newtype ListMaxResults = ListMaxResults Int
derive instance newtypeListMaxResults :: Newtype ListMaxResults _


newtype ListParentArnList = ListParentArnList (Array Arn)
derive instance newtypeListParentArnList :: Newtype ListParentArnList _


newtype ListReturnedArnList = ListReturnedArnList (Array Arn)
derive instance newtypeListReturnedArnList :: Newtype ListReturnedArnList _


newtype ListRulesPackagesRequest = ListRulesPackagesRequest 
  { "NextToken'" :: NullOrUndefined (PaginationToken)
  , "MaxResults'" :: NullOrUndefined (ListMaxResults)
  }
derive instance newtypeListRulesPackagesRequest :: Newtype ListRulesPackagesRequest _


newtype ListRulesPackagesResponse = ListRulesPackagesResponse 
  { "RulesPackageArns'" :: (ListReturnedArnList)
  , "NextToken'" :: NullOrUndefined (PaginationToken)
  }
derive instance newtypeListRulesPackagesResponse :: Newtype ListRulesPackagesResponse _


newtype ListTagsForResourceRequest = ListTagsForResourceRequest 
  { "ResourceArn'" :: (Arn)
  }
derive instance newtypeListTagsForResourceRequest :: Newtype ListTagsForResourceRequest _


newtype ListTagsForResourceResponse = ListTagsForResourceResponse 
  { "Tags'" :: (TagList)
  }
derive instance newtypeListTagsForResourceResponse :: Newtype ListTagsForResourceResponse _


newtype Locale = Locale String
derive instance newtypeLocale :: Newtype Locale _


newtype Message = Message String
derive instance newtypeMessage :: Newtype Message _


newtype MessageType = MessageType String
derive instance newtypeMessageType :: Newtype MessageType _


newtype NamePattern = NamePattern String
derive instance newtypeNamePattern :: Newtype NamePattern _


newtype NoSuchEntityErrorCode = NoSuchEntityErrorCode String
derive instance newtypeNoSuchEntityErrorCode :: Newtype NoSuchEntityErrorCode _


-- | <p>The request was rejected because it referenced an entity that does not exist. The error code describes the entity.</p>
newtype NoSuchEntityException = NoSuchEntityException 
  { "Message'" :: (ErrorMessage)
  , "ErrorCode'" :: (NoSuchEntityErrorCode)
  , "CanRetry'" :: (Bool)
  }
derive instance newtypeNoSuchEntityException :: Newtype NoSuchEntityException _


newtype NumericSeverity = NumericSeverity Number
derive instance newtypeNumericSeverity :: Newtype NumericSeverity _


newtype NumericVersion = NumericVersion Int
derive instance newtypeNumericVersion :: Newtype NumericVersion _


newtype OperatingSystem = OperatingSystem String
derive instance newtypeOperatingSystem :: Newtype OperatingSystem _


newtype PaginationToken = PaginationToken String
derive instance newtypePaginationToken :: Newtype PaginationToken _


newtype PreviewAgentsMaxResults = PreviewAgentsMaxResults Int
derive instance newtypePreviewAgentsMaxResults :: Newtype PreviewAgentsMaxResults _


newtype PreviewAgentsRequest = PreviewAgentsRequest 
  { "PreviewAgentsArn'" :: (Arn)
  , "NextToken'" :: NullOrUndefined (PaginationToken)
  , "MaxResults'" :: NullOrUndefined (PreviewAgentsMaxResults)
  }
derive instance newtypePreviewAgentsRequest :: Newtype PreviewAgentsRequest _


newtype PreviewAgentsResponse = PreviewAgentsResponse 
  { "AgentPreviews'" :: (AgentPreviewList)
  , "NextToken'" :: NullOrUndefined (PaginationToken)
  }
derive instance newtypePreviewAgentsResponse :: Newtype PreviewAgentsResponse _


newtype ProviderName = ProviderName String
derive instance newtypeProviderName :: Newtype ProviderName _


newtype RegisterCrossAccountAccessRoleRequest = RegisterCrossAccountAccessRoleRequest 
  { "RoleArn'" :: (Arn)
  }
derive instance newtypeRegisterCrossAccountAccessRoleRequest :: Newtype RegisterCrossAccountAccessRoleRequest _


newtype RemoveAttributesFromFindingsRequest = RemoveAttributesFromFindingsRequest 
  { "FindingArns'" :: (AddRemoveAttributesFindingArnList)
  , "AttributeKeys'" :: (UserAttributeKeyList)
  }
derive instance newtypeRemoveAttributesFromFindingsRequest :: Newtype RemoveAttributesFromFindingsRequest _


newtype RemoveAttributesFromFindingsResponse = RemoveAttributesFromFindingsResponse 
  { "FailedItems'" :: (FailedItems)
  }
derive instance newtypeRemoveAttributesFromFindingsResponse :: Newtype RemoveAttributesFromFindingsResponse _


newtype ReportFileFormat = ReportFileFormat String
derive instance newtypeReportFileFormat :: Newtype ReportFileFormat _


newtype ReportStatus = ReportStatus String
derive instance newtypeReportStatus :: Newtype ReportStatus _


newtype ReportType = ReportType String
derive instance newtypeReportType :: Newtype ReportType _


-- | <p>Contains information about a resource group. The resource group defines a set of tags that, when queried, identify the AWS resources that make up the assessment target. This data type is used as the response element in the <a>DescribeResourceGroups</a> action.</p>
newtype ResourceGroup = ResourceGroup 
  { "Arn'" :: (Arn)
  , "Tags'" :: (ResourceGroupTags)
  , "CreatedAt'" :: (Number)
  }
derive instance newtypeResourceGroup :: Newtype ResourceGroup _


newtype ResourceGroupList = ResourceGroupList (Array ResourceGroup)
derive instance newtypeResourceGroupList :: Newtype ResourceGroupList _


-- | <p>This data type is used as one of the elements of the <a>ResourceGroup</a> data type.</p>
newtype ResourceGroupTag = ResourceGroupTag 
  { "Key'" :: (TagKey)
  , "Value'" :: NullOrUndefined (TagValue)
  }
derive instance newtypeResourceGroupTag :: Newtype ResourceGroupTag _


newtype ResourceGroupTags = ResourceGroupTags (Array ResourceGroupTag)
derive instance newtypeResourceGroupTags :: Newtype ResourceGroupTags _


newtype RuleName = RuleName String
derive instance newtypeRuleName :: Newtype RuleName _


newtype RuleNameList = RuleNameList (Array RuleName)
derive instance newtypeRuleNameList :: Newtype RuleNameList _


-- | <p>Contains information about an Amazon Inspector rules package. This data type is used as the response element in the <a>DescribeRulesPackages</a> action.</p>
newtype RulesPackage = RulesPackage 
  { "Arn'" :: (Arn)
  , "Name'" :: (RulesPackageName)
  , "Version'" :: (Version)
  , "Provider'" :: (ProviderName)
  , "Description'" :: NullOrUndefined (Text)
  }
derive instance newtypeRulesPackage :: Newtype RulesPackage _


newtype RulesPackageList = RulesPackageList (Array RulesPackage)
derive instance newtypeRulesPackageList :: Newtype RulesPackageList _


newtype RulesPackageName = RulesPackageName String
derive instance newtypeRulesPackageName :: Newtype RulesPackageName _


newtype ServiceName = ServiceName String
derive instance newtypeServiceName :: Newtype ServiceName _


newtype SetTagsForResourceRequest = SetTagsForResourceRequest 
  { "ResourceArn'" :: (Arn)
  , "Tags'" :: NullOrUndefined (TagList)
  }
derive instance newtypeSetTagsForResourceRequest :: Newtype SetTagsForResourceRequest _


newtype Severity = Severity String
derive instance newtypeSeverity :: Newtype Severity _


newtype SeverityList = SeverityList (Array Severity)
derive instance newtypeSeverityList :: Newtype SeverityList _


newtype StartAssessmentRunRequest = StartAssessmentRunRequest 
  { "AssessmentTemplateArn'" :: (Arn)
  , "AssessmentRunName'" :: NullOrUndefined (AssessmentRunName)
  }
derive instance newtypeStartAssessmentRunRequest :: Newtype StartAssessmentRunRequest _


newtype StartAssessmentRunResponse = StartAssessmentRunResponse 
  { "AssessmentRunArn'" :: (Arn)
  }
derive instance newtypeStartAssessmentRunResponse :: Newtype StartAssessmentRunResponse _


newtype StopAction = StopAction String
derive instance newtypeStopAction :: Newtype StopAction _


newtype StopAssessmentRunRequest = StopAssessmentRunRequest 
  { "AssessmentRunArn'" :: (Arn)
  , "StopAction'" :: NullOrUndefined (StopAction)
  }
derive instance newtypeStopAssessmentRunRequest :: Newtype StopAssessmentRunRequest _


newtype SubscribeToEventRequest = SubscribeToEventRequest 
  { "ResourceArn'" :: (Arn)
  , "Event'" :: (InspectorEvent)
  , "TopicArn'" :: (Arn)
  }
derive instance newtypeSubscribeToEventRequest :: Newtype SubscribeToEventRequest _


-- | <p>This data type is used as a response element in the <a>ListEventSubscriptions</a> action.</p>
newtype Subscription = Subscription 
  { "ResourceArn'" :: (Arn)
  , "TopicArn'" :: (Arn)
  , "EventSubscriptions'" :: (EventSubscriptionList)
  }
derive instance newtypeSubscription :: Newtype Subscription _


newtype SubscriptionList = SubscriptionList (Array Subscription)
derive instance newtypeSubscriptionList :: Newtype SubscriptionList _


-- | <p>A key and value pair. This data type is used as a request parameter in the <a>SetTagsForResource</a> action and a response element in the <a>ListTagsForResource</a> action.</p>
newtype Tag = Tag 
  { "Key'" :: (TagKey)
  , "Value'" :: NullOrUndefined (TagValue)
  }
derive instance newtypeTag :: Newtype Tag _


newtype TagKey = TagKey String
derive instance newtypeTagKey :: Newtype TagKey _


newtype TagList = TagList (Array Tag)
derive instance newtypeTagList :: Newtype TagList _


newtype TagValue = TagValue String
derive instance newtypeTagValue :: Newtype TagValue _


-- | <p>The metadata about the Amazon Inspector application data metrics collected by the agent. This data type is used as the response element in the <a>GetTelemetryMetadata</a> action.</p>
newtype TelemetryMetadata = TelemetryMetadata 
  { "MessageType'" :: (MessageType)
  , "Count'" :: (Number)
  , "DataSize'" :: NullOrUndefined (Number)
  }
derive instance newtypeTelemetryMetadata :: Newtype TelemetryMetadata _


newtype TelemetryMetadataList = TelemetryMetadataList (Array TelemetryMetadata)
derive instance newtypeTelemetryMetadataList :: Newtype TelemetryMetadataList _


newtype Text = Text String
derive instance newtypeText :: Newtype Text _


-- | <p>This data type is used in the <a>AssessmentRunFilter</a> data type.</p>
newtype TimestampRange = TimestampRange 
  { "BeginDate'" :: NullOrUndefined (Number)
  , "EndDate'" :: NullOrUndefined (Number)
  }
derive instance newtypeTimestampRange :: Newtype TimestampRange _


newtype UnsubscribeFromEventRequest = UnsubscribeFromEventRequest 
  { "ResourceArn'" :: (Arn)
  , "Event'" :: (InspectorEvent)
  , "TopicArn'" :: (Arn)
  }
derive instance newtypeUnsubscribeFromEventRequest :: Newtype UnsubscribeFromEventRequest _


-- | <p>Used by the <a>GetAssessmentReport</a> API. The request was rejected because you tried to generate a report for an assessment run that existed before reporting was supported in Amazon Inspector. You can only generate reports for assessment runs that took place or will take place after generating reports in Amazon Inspector became available.</p>
newtype UnsupportedFeatureException = UnsupportedFeatureException 
  { "Message'" :: (ErrorMessage)
  , "CanRetry'" :: (Bool)
  }
derive instance newtypeUnsupportedFeatureException :: Newtype UnsupportedFeatureException _


newtype UpdateAssessmentTargetRequest = UpdateAssessmentTargetRequest 
  { "AssessmentTargetArn'" :: (Arn)
  , "AssessmentTargetName'" :: (AssessmentTargetName)
  , "ResourceGroupArn'" :: (Arn)
  }
derive instance newtypeUpdateAssessmentTargetRequest :: Newtype UpdateAssessmentTargetRequest _


newtype Url = Url String
derive instance newtypeUrl :: Newtype Url _


newtype UserAttributeKeyList = UserAttributeKeyList (Array AttributeKey)
derive instance newtypeUserAttributeKeyList :: Newtype UserAttributeKeyList _


newtype UserAttributeList = UserAttributeList (Array Attribute)
derive instance newtypeUserAttributeList :: Newtype UserAttributeList _


newtype Version = Version String
derive instance newtypeVersion :: Newtype Version _
